package cscw.crm.core.entity;

import java.util.Date;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String deptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.superdeptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String superdeptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String deptname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dept_level
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean deptLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptclass
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String deptclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.creator
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.managerstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String managerstaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.managerstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String managerstaffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.phone
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.fax
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.addr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Short staffnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.ordernum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.commfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Float commfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.foreignfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Float foreignfee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.isleaf
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean isleaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.isdeleted
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean isdeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.auditstate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean auditstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.remark
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String inputstaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String inputstaffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date inputdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.lastmender
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String lastmender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.lastupdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date lastupdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String deptnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.parentdeptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String parentdeptnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.status
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dealtrack
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String dealtrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.handler
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.intr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String intr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.effective
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean effective;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.flow
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Short flow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.managerstaffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String managerstaffnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptid
     *
     * @return the value of dept.deptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getDeptid() {
        return deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptid
     *
     * @param deptid the value for dept.deptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDeptid(String deptid) {
        this.deptid = deptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.superdeptid
     *
     * @return the value of dept.superdeptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getSuperdeptid() {
        return superdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.superdeptid
     *
     * @param superdeptid the value for dept.superdeptid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setSuperdeptid(String superdeptid) {
        this.superdeptid = superdeptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptname
     *
     * @return the value of dept.deptname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getDeptname() {
        return deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptname
     *
     * @param deptname the value for dept.deptname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dept_level
     *
     * @return the value of dept.dept_level
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getDeptLevel() {
        return deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dept_level
     *
     * @param deptLevel the value for dept.dept_level
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDeptLevel(Boolean deptLevel) {
        this.deptLevel = deptLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptclass
     *
     * @return the value of dept.deptclass
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getDeptclass() {
        return deptclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptclass
     *
     * @param deptclass the value for dept.deptclass
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDeptclass(String deptclass) {
        this.deptclass = deptclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.createtime
     *
     * @return the value of dept.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.createtime
     *
     * @param createtime the value for dept.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.creator
     *
     * @return the value of dept.creator
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.creator
     *
     * @param creator the value for dept.creator
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.managerstaffid
     *
     * @return the value of dept.managerstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getManagerstaffid() {
        return managerstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.managerstaffid
     *
     * @param managerstaffid the value for dept.managerstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setManagerstaffid(String managerstaffid) {
        this.managerstaffid = managerstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.managerstaffname
     *
     * @return the value of dept.managerstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getManagerstaffname() {
        return managerstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.managerstaffname
     *
     * @param managerstaffname the value for dept.managerstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setManagerstaffname(String managerstaffname) {
        this.managerstaffname = managerstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.phone
     *
     * @return the value of dept.phone
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.phone
     *
     * @param phone the value for dept.phone
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.fax
     *
     * @return the value of dept.fax
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.fax
     *
     * @param fax the value for dept.fax
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.addr
     *
     * @return the value of dept.addr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.addr
     *
     * @param addr the value for dept.addr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.staffnum
     *
     * @return the value of dept.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Short getStaffnum() {
        return staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.staffnum
     *
     * @param staffnum the value for dept.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setStaffnum(Short staffnum) {
        this.staffnum = staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.ordernum
     *
     * @return the value of dept.ordernum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.ordernum
     *
     * @param ordernum the value for dept.ordernum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setOrdernum(Boolean ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.commfee
     *
     * @return the value of dept.commfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Float getCommfee() {
        return commfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.commfee
     *
     * @param commfee the value for dept.commfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setCommfee(Float commfee) {
        this.commfee = commfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.foreignfee
     *
     * @return the value of dept.foreignfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Float getForeignfee() {
        return foreignfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.foreignfee
     *
     * @param foreignfee the value for dept.foreignfee
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setForeignfee(Float foreignfee) {
        this.foreignfee = foreignfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.isleaf
     *
     * @return the value of dept.isleaf
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getIsleaf() {
        return isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.isleaf
     *
     * @param isleaf the value for dept.isleaf
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIsleaf(Boolean isleaf) {
        this.isleaf = isleaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.isdeleted
     *
     * @return the value of dept.isdeleted
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getIsdeleted() {
        return isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.isdeleted
     *
     * @param isdeleted the value for dept.isdeleted
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIsdeleted(Boolean isdeleted) {
        this.isdeleted = isdeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.auditstate
     *
     * @return the value of dept.auditstate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getAuditstate() {
        return auditstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.auditstate
     *
     * @param auditstate the value for dept.auditstate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setAuditstate(Boolean auditstate) {
        this.auditstate = auditstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.remark
     *
     * @return the value of dept.remark
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.remark
     *
     * @param remark the value for dept.remark
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.inputstaffid
     *
     * @return the value of dept.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getInputstaffid() {
        return inputstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.inputstaffid
     *
     * @param inputstaffid the value for dept.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputstaffid(String inputstaffid) {
        this.inputstaffid = inputstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.inputstaffname
     *
     * @return the value of dept.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getInputstaffname() {
        return inputstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.inputstaffname
     *
     * @param inputstaffname the value for dept.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputstaffname(String inputstaffname) {
        this.inputstaffname = inputstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.inputdate
     *
     * @return the value of dept.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.inputdate
     *
     * @param inputdate the value for dept.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.lastmender
     *
     * @return the value of dept.lastmender
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getLastmender() {
        return lastmender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.lastmender
     *
     * @param lastmender the value for dept.lastmender
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setLastmender(String lastmender) {
        this.lastmender = lastmender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.lastupdate
     *
     * @return the value of dept.lastupdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.lastupdate
     *
     * @param lastupdate the value for dept.lastupdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptnum
     *
     * @return the value of dept.deptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getDeptnum() {
        return deptnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptnum
     *
     * @param deptnum the value for dept.deptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDeptnum(String deptnum) {
        this.deptnum = deptnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.parentdeptnum
     *
     * @return the value of dept.parentdeptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getParentdeptnum() {
        return parentdeptnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.parentdeptnum
     *
     * @param parentdeptnum the value for dept.parentdeptnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setParentdeptnum(String parentdeptnum) {
        this.parentdeptnum = parentdeptnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.status
     *
     * @return the value of dept.status
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.status
     *
     * @param status the value for dept.status
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dealtrack
     *
     * @return the value of dept.dealtrack
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getDealtrack() {
        return dealtrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dealtrack
     *
     * @param dealtrack the value for dept.dealtrack
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setDealtrack(String dealtrack) {
        this.dealtrack = dealtrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.handler
     *
     * @return the value of dept.handler
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.handler
     *
     * @param handler the value for dept.handler
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setHandler(String handler) {
        this.handler = handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.intr
     *
     * @return the value of dept.intr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getIntr() {
        return intr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.intr
     *
     * @param intr the value for dept.intr
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIntr(String intr) {
        this.intr = intr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.effective
     *
     * @return the value of dept.effective
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getEffective() {
        return effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.effective
     *
     * @param effective the value for dept.effective
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setEffective(Boolean effective) {
        this.effective = effective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.flow
     *
     * @return the value of dept.flow
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Short getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.flow
     *
     * @param flow the value for dept.flow
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setFlow(Short flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.managerstaffnum
     *
     * @return the value of dept.managerstaffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getManagerstaffnum() {
        return managerstaffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.managerstaffnum
     *
     * @param managerstaffnum the value for dept.managerstaffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setManagerstaffnum(String managerstaffnum) {
        this.managerstaffnum = managerstaffnum;
    }
}