package cscw.crm.core.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.rolename
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String rolename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roledesc
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String roledesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String inputstaffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String inputstaffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date inputdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleid
     *
     * @return the value of role.roleid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleid
     *
     * @param roleid the value for role.roleid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.rolename
     *
     * @return the value of role.rolename
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.rolename
     *
     * @param rolename the value for role.rolename
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roledesc
     *
     * @return the value of role.roledesc
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getRoledesc() {
        return roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roledesc
     *
     * @param roledesc the value for role.roledesc
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setRoledesc(String roledesc) {
        this.roledesc = roledesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.inputstaffid
     *
     * @return the value of role.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getInputstaffid() {
        return inputstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.inputstaffid
     *
     * @param inputstaffid the value for role.inputstaffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputstaffid(String inputstaffid) {
        this.inputstaffid = inputstaffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.inputstaffname
     *
     * @return the value of role.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getInputstaffname() {
        return inputstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.inputstaffname
     *
     * @param inputstaffname the value for role.inputstaffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputstaffname(String inputstaffname) {
        this.inputstaffname = inputstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.inputdate
     *
     * @return the value of role.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getInputdate() {
        return inputdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.inputdate
     *
     * @param inputdate the value for role.inputdate
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }
}