package cscw.crm.core.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import java.util.Date;

@Entity
public class User{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    @Id
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.staffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String staffid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.username
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.issupervisor
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean issupervisor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.isuse
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean isuse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.islocked
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Boolean islocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lockedtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date lockedtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.valicode
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String valicode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lifetime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private Date lifetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.staffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String staffname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    private String staffnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userid
     *
     * @return the value of user.userid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userid
     *
     * @param userid the value for user.userid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.staffid
     *
     * @return the value of user.staffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getStaffid() {
        return staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.staffid
     *
     * @param staffid the value for user.staffid
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.username
     *
     * @return the value of user.username
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.username
     *
     * @param username the value for user.username
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.issupervisor
     *
     * @return the value of user.issupervisor
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getIssupervisor() {
        return issupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.issupervisor
     *
     * @param issupervisor the value for user.issupervisor
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIssupervisor(Boolean issupervisor) {
        this.issupervisor = issupervisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.isuse
     *
     * @return the value of user.isuse
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.isuse
     *
     * @param isuse the value for user.isuse
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIsuse(Boolean isuse) {
        this.isuse = isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.islocked
     *
     * @return the value of user.islocked
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Boolean getIslocked() {
        return islocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.islocked
     *
     * @param islocked the value for user.islocked
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setIslocked(Boolean islocked) {
        this.islocked = islocked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lockedtime
     *
     * @return the value of user.lockedtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getLockedtime() {
        return lockedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lockedtime
     *
     * @param lockedtime the value for user.lockedtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setLockedtime(Date lockedtime) {
        this.lockedtime = lockedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.valicode
     *
     * @return the value of user.valicode
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getValicode() {
        return valicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.valicode
     *
     * @param valicode the value for user.valicode
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setValicode(String valicode) {
        this.valicode = valicode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createtime
     *
     * @return the value of user.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createtime
     *
     * @param createtime the value for user.createtime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lifetime
     *
     * @return the value of user.lifetime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public Date getLifetime() {
        return lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lifetime
     *
     * @param lifetime the value for user.lifetime
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setLifetime(Date lifetime) {
        this.lifetime = lifetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.staffname
     *
     * @return the value of user.staffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getStaffname() {
        return staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.staffname
     *
     * @param staffname the value for user.staffname
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.staffnum
     *
     * @return the value of user.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public String getStaffnum() {
        return staffnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.staffnum
     *
     * @param staffnum the value for user.staffnum
     *
     * @mbggenerated Thu Nov 24 14:59:10 CST 2016
     */
    public void setStaffnum(String staffnum) {
        this.staffnum = staffnum;
    }
}